### ISSUE TITLE
POMME assumes that characters are signed; this is false.

### ISSUE THREAD

**Issue by NoelJB** [jorio/BillyFrontier#5]
Building Billy Frontier on Linux with gcc 12, I get:

```
.../billy-frontier/src/billy-frontier/Source/System/Main.c: In function ‘PlayGame_Arcade’:
.../billy-frontier/src/billy-frontier/Source/System/Main.c:163:55: warning: comparison is always false due to limited range of data type [-Wtype-limits]
  163 |                                 if (gPlayerInfo.lives < 0)
      |                                                       ^
.../billy-frontier/src/billy-frontier/Source/System/Main.c:217:47: warning: comparison is always false due to limited range of data type [-Wtype-limits]
  217 |                         if (gPlayerInfo.lives < 0)
      |                                               ^
```

In `player.h`, the definition of `lives` is `SInt8`.  That's an old Apple datatype, which you have defined in Pomme.  The problem is that Pomme defines it as `typedef char SInt8;`, but `char` is unsigned as per the C Language Specification, leading to the above.

**Comment by jorio** [comment]
Good catch! I assume you're using aarch64?

The C spec leaves the signedness of char up to the platform to define. It happens to be signed on x86_64 but it is indeed unsigned on aarch64 (on Linux at least...)

I changed the typedefs to int*_t types from stdint.h for better portability.

Please try to recompile and let me know if there are other issues.

**Comment by NoelJB** [comment]
Yes, I built all of your ports for the PineTab2, so aarch64.  :-)  Since you hadn't used the standard int typedefs for anything, I didn't want to presume that you would, but  `int8_t` and company would be the best approach.

I had come across a claim that the "default" is unsigned, but you are correct that the spec is explicitly ambivalent, which is not a good thing for portability.  I just looked at the current C Language specification.  Technically, 6.2.5.3 appears to say that plain `char` should be used only in relation to character set data, with the next part saying, "There are five standard signed integer types, designated as signed char, short int, int, long int, and long long int" and "For each of the signed integer types, there is a corresponding (but different) unsigned integer type (designated with the keyword unsigned)", but elsewhere lumps it in with them.

**Comment by jorio** [comment]
Yeah, it's definitely an odd design choice to enforce that all integer types be signed by default except for char. From now on I won't trust char for storing numeric values in cross-platform code, unless it's qualified with signed or unsigned.

Thanks for bringing this up! I'm closing the issue because it's fixed on master. Feel free to reopen if the game craps out elsewhere due to sign problems.
